# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-14 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line_Chart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_January', models.IntegerField()),
                ('a_February', models.IntegerField()),
                ('a_March', models.IntegerField()),
                ('a_April', models.IntegerField()),
                ('a_May', models.IntegerField()),
                ('a_June', models.IntegerField()),
                ('a_July', models.IntegerField()),
                ('a_August', models.IntegerField()),
                ('a_September', models.IntegerField()),
                ('a_October', models.IntegerField()),
                ('a_November', models.IntegerField()),
                ('a_December', models.IntegerField()),
            ],
        ),
    ]
